### PR TITLE
[OSD-15192] Empty commit to trigger a rebuild.

### PR DESCRIPTION
**Pull request by bergmannf**
This is related to [OSD-15192](https://issues.redhat.com//browse/OSD-15192) to rebase the aws-account-shredder image to the newest baseimage.

### CODE REVIEW

**Review by dkeohane — APPROVED** [review]
/approve
/lgtm

**Comment by iamkirkbater** [comment]
We're seeing this same issue across other repos, with the empty commit not working to trigger a new build.  I'm going to close this and we'll have to find another way.

/close

**Pull request closed without merging**
